services:
    rares_image_crop.form.type.crop_image:
        class: Rares\ImageCropBundle\Form\Type\CropImageType
        arguments:
            - "@rares_image_crop.helper.image"
        tags:
            - { name: form.type, alias: 'rares_image_crop_crop_image' }

    rares_image_crop.helper.image:
        class: Rares\ImageCropBundle\Helper\ImageHelper
